apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-local-object-store-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: local-object-store
  # annotations:
    # Ciliumで特定のIPアドレスを割り当てる場合
    # io.cilium/lb-ipam-ips: "192.168.1.100"
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    # HTTPSを有効にする場合は以下をコメント解除
    # - name: https
    #   port: 443
    #   protocol: TCP
    #   targetPort: 443
  selector:
    app: rook-ceph-rgw
    ceph_daemon_id: local-object-store
    rgw: local-object-store
    rook_cluster: rook-ceph
    rook_object_store: local-object-store
